name       : numix-icon-theme-square
version    : 21.08.14
release    : 20
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/21.08.14.tar.gz : 7246407d598d8647c1d817f382a2e1c53531c0e0e915efbed344a633de959292
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
