name       : numix-icon-theme-square
version    : 22.02.06
release    : 23
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/22.02.06.tar.gz : d58ce022bac801445e6bc9cf85b9373651f4186f7c7ed967f760806076662742
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
