name       : numix-icon-theme-square
version    : 19.05.07
release    : 14
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/19.05.07.tar.gz : 0785246749a21f2c28073bca27a2408efff1e506ab7f260731e30fa13aa8f7e3
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r Numix-Square $installdir/usr/share/icons/
    cp -r Numix-Square-Light $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
