name       : numix-icon-theme-square
version    : 18.04.04
release    : 4
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/18-04-04.tar.gz : 1d11279f21545b0f8780acf4bf92d9121c9e5f5cd84a8060264dc09de96a6827
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r Numix-Square $installdir/usr/share/icons/
    cp -r Numix-Square-Light $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
