name       : numix-icon-theme-square
version    : 22.03.01
release    : 24
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/22.03.01.tar.gz : a39e97d7117e4857e8226d0cef625d167fb7b8cc449e6007e31daaa9d4adff4b
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
