name       : numix-icon-theme-square
version    : 23.04.28
release    : 31
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/23.04.28.tar.gz : 12eecbca79172b3444f3987d06f9dbe0f74f36301d60c41ea8487d28a488bad0
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
