name       : numix-icon-theme-square
version    : 19.12.27
release    : 16
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/19.12.27.tar.gz : a335667f6d2520e4dcf40b1eea6eeacc1566c31947f1421004fdab02882bc84e
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
