name       : numix-icon-theme-square
version    : 20.06.07
release    : 17
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/20.06.07.tar.gz : 309d99e9ac8acfea978f995a616b6db5315610b6a11f291bcb0e1f08f66cf3c5
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
