name       : numix-icon-theme-square
version    : 23.07.08
release    : 34
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/23.07.08.tar.gz : 953000db5bfc820b338ea1700ef94e426672bd99455a922d65c24e7a7171d2af
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
