name       : numix-icon-theme-square
version    : 20.09.19
release    : 18
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/20.09.19.tar.gz : 664bfe0f7646121db7517b5a38c9df14be9e7d9bf4dec680d62b211b71b63138
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
