name       : numix-icon-theme-square
version    : 23.01.13
release    : 29
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/23.01.12.tar.gz : 80ef562aeb79d95458551c0ca93e2d48e2248639787a33068179a4ba6f4bb5e3
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
