name       : numix-icon-theme-square
version    : 22.01.10
release    : 22
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/22.01.10.tar.gz : dd80e9f711fbb7587eaae0d17f383038c0fcf21ffad9aa0c29140f88132482a8
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
