name       : numix-icon-theme-square
version    : 23.06.21
release    : 33
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/23.06.21.tar.gz : 399744c88250ec65855813fd244d79388f2b21dc030ea76c74ddc627aa0030d9
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
